### ISSUE TITLE
"java -jar Peergos.jar migrate" comes out "This+server+is+not+currently+accepting+new+user+migrations"

### ISSUE THREAD

**Issue by chungyan5** [Peergos/Peergos#1206]
hi all, 

I am new in IPFS and Peergos, so want to setup Peergos to get concept of them. 

I setup THREE instances at my three notebooks by "java -jar Peergos.jar daemon ...". All are running and can inter-login my few login accounts. I am going to try TWO notebooks with all data for one login account, NOT only one home server and others as proxy only. So I try "java -jar Peergos.jar migrate", however, i got this msg. "This+server+is+not+currently+accepting+new+user+migrations", i do not have idea for further steps to settle this issue. 

Do i go a wrong direction? I would like to try to pin one user data in two noteooks, and all accounts data at another two notebooks, i guess should be "java -jar Peergos.jar mirror init ...", not yet try. 

I am appreciation if anyone to give me some hints. 

thanks
chungyan5

**Comment by ianopolous** [comment]
If you want to mirror a users data then you need to follow the instructions in the readme.

Which server address did you try to migrate to? peergos.net is not currently accepting migrations.

**Comment by chungyan5** [comment]
Dear ianopolous, 

I would like to try inside my self-hosting peergos between my testing notebooks, not peergos.net. 

> follow the instructions in the readme
i tried this "java -jar Peergos.jar migrate" in notebook #2, then input my username "yan" comes from notebook #1 (i tried `java -jar Peergos.jar usage show` and see my name "yan", but NOT at notebook #2)

> Which server address did you try to migrate to?
Do you mean i need to specific the IP of notebook #2 and #1 ? 

thanks

**Comment by ianopolous** [comment]
You need the address of the server you want to migrate to. If it is not a public server, then you need to run the migrate command on that server and use http://localhost:8000

**Comment by chungyan5** [comment]
I tried this 

C:\PortableApps\Peergos>**java -jar Peergos.jar migrate -help**
migrate: Move a Peergos account to this server.
Parameters:
        peergos-url: Address of the Peergos server to migrate to

C:\PortableApps\Peergos>**java -jar Peergos.jar migrate -peergos-url http://localhost:8000/**
Enter username to migrate to this server: yan
Enter password for yan:
`Migrating user from node z5AanNVJCxnRLyYBjvyGkQbJgwEGZguXytStwjSZTqzbFRG7PY5qv3Y to z5AanNVJCxnJ5NqvPBUDVWzbSroohSvUgX1v3g4UdVDdWT1FiHidruB
Trailer:Optional[This+server+is+not+currently+accepting+new+user+migrations.]
java.util.concurrent.CompletionException: java.lang.RuntimeException: This+server+is+not+currently+accepting+new+user+migrations.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
        at peergos.shared.corenode.HTTPCoreNode.migrateUser(HTTPCoreNode.java:278)
        at peergos.shared.corenode.TofuCoreNode.migrateUser(TofuCoreNode.java:183)
        at peergos.server.Main.migrate(Main.java:898)
        at peergos.server.Command.main(Command.java:75)
        at peergos.server.Command.main(Command.java:63)
        at peergos.server.Main.main(Main.java:952)
Caused by: java.lang.RuntimeException: This+server+is+not+currently+accepting+new+user+migrations.
        at peergos.server.util.JavaPoster.handleError(JavaPoster.java:107)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:83)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:50)
        at peergos.server.util.JavaPoster.postUnzip(JavaPoster.java:45)
        at peergos.shared.corenode.HTTPCoreNode.migrateUser(HTTPCoreNode.java:277)
        ... 5 more `

Still have this issue

**Comment by chungyan5** [comment]
i added `-log-to-console true`, it comes out timeout error

`C:\PortableApps\Peergos>java -jar Peergos.jar migrate -peergos-url http://localhost:8000/ -log-to-console true
Oct 08, 2024 4:43:33 PM peergos.server.util.Logging init
INFO: Logging to C:\Users\SAMSUNG\.peergos\peergos.0.log
Oct 08, 2024 4:43:33 PM peergos.shared.corenode.HTTPCoreNode <init>
INFO: Creating HTTP Corenode API at http://localhost:8000/
Oct 08, 2024 4:43:33 PM peergos.shared.mutable.HttpMutablePointers <init>
INFO: Creating Http Mutable Pointers API at http://localhost:8000/ and http://localhost:8000/
Oct 08, 2024 4:43:33 PM peergos.shared.social.HttpSocialNetwork <init>
INFO: Creating HTTP SocialNetwork API at http://localhost:8000/ and http://localhost:8000/
Oct 08, 2024 4:43:33 PM peergos.shared.storage.HttpSpaceUsage <init>
INFO: Creating HTTP SpaceUsage API at http://localhost:8000/ and http://localhost:8000/
Enter username to migrate to this server: yan
Enter password for yan:
Oct 08, 2024 4:43:39 PM peergos.shared.mutable.HttpMutablePointers getPointer
INFO: HttpMutablePointers.get took 40mS for (z59vuwzfFDoqtUsSEFmNj5GrSzQbdgj6Dn2r8hHMQGHbPmouiXR2ZnC, z59vuwzfFDoqtUsSEFmNj5GrSzQbdgj6Dn2r8hHMQGHbPmouiXR2ZnC)
Oct 08, 2024 4:43:40 PM peergos.server.crypto.hash.ScryptJava hashToKeyBytes
INFO: Scrypt hashing took: 915 mS
java.util.concurrent.CompletionException: java.net.SocketTimeoutException: Socket timeout on: peergos/v0/login/getLogin?username=yan&author=820158204def2b13cd63919334cb3ffd8be62a396d79015b934eaac5972d6614e0604312&auth=5e7c5e86f741e62768715a77fb5afb63e9856382083751ddc20e9f6743b1c2c1f06af00452b1b560337f7281dfacef8cc33669a2731c7bb6b91daa6fe67b68051b000001926b4c5f69
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
        at peergos.shared.user.HttpAccount.getLoginData(HttpAccount.java:89)
        at peergos.shared.user.HttpAccount.getLoginData(HttpAccount.java:67)
        at peergos.shared.user.UserContext.lambda$getLoginData$13(UserContext.java:217)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
        at peergos.shared.user.UserContext.getLoginData(UserContext.java:217)
        at peergos.shared.user.UserContext.login(UserContext.java:249)
        at peergos.shared.user.UserContext.lambda$signIn$8(UserContext.java:169)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
        at peergos.shared.user.UserContext.lambda$signIn$9(UserContext.java:167)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)
        at peergos.shared.user.UserContext.signIn(UserContext.java:161)
        at peergos.shared.user.UserContext.signIn(UserContext.java:142)
        at peergos.server.Main.migrate(Main.java:885)
        at peergos.server.Command.main(Command.java:75)
        at peergos.server.Command.main(Command.java:63)
        at peergos.server.Main.main(Main.java:952) ... `

**Comment by ianopolous** [comment]
Is the server you are migrating to publicly routeable? (Does it have a public ip address?)

**Comment by chungyan5** [comment]
> Is the server you are migrating to publicly routeable?

NO, it is inside my home intranet

**Comment by ianopolous** [comment]
Oh you currently can only to migrate to a server that is publically routable, because you need to be able to dial it. We do not have NAT traversal implemented yet.

**Comment by chungyan5** [comment]
Thks Ianopolous.

**Comment by chungyan5** [comment]
I hope i do not mis-understand Peergos approch. My wishlist as: 1) not pinning whole data set for one user. eg. say, i have 6T data, i must pin into one peergos instance with >6T storage, i hope they can split and distribute into different computers with small storage size, and group together >6T 2) i can pin the data set as like a duplicated set(backup) into my another computers (usually inside NAT - not have public IP)

**Comment by rapenne-s** [comment]
> I hope i do not mis-understand Peergos currently approach. My wishlist as: 1) not pinning whole data set for one user at one instance. eg. say, i have 6T data, i must pin into one peergos instance with >6T storage, i hope they can split and distribute into different computers with small storage size, and group together >6T 2) i can pin the data set as like a duplicated set(backup) into my another computers (usually inside NAT - not have public IP)

1) Peergos stores everything in an instance, then a proxy instance can be used as a client with a local cache, but the storage is not distributed in Peergos. As far as I understood Peergos architecture.

2) yes, you can have a mirror of a user data, but not partial, so if that user has 6 TB the mirror will hold 6 TB too

there is now a sync client that sync 1 or more local directory(ies) with Peergos directories, so you can have a local partial checkout of Peergos.
