### ISSUE TITLE
[bug] command line peergos does not support webauthn

### ISSUE THREAD

**Issue by rapenne-s** [Peergos/Peergos#1216]
If only a passkey is used for MFA, peergos is not usable in command line

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: No supported 2 factor auth method! [MultiFactorAuthMethod{uid='13f008b8b1384682a5b2344840c2bda5', type=WEBAUTHN, enabled=true}]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalStateException: No supported 2 factor auth method! [MultiFactorAuthMethod{uid='13f008b8b1384682a5b2344840c2bda5', type=WEBAUTHN, enabled=true}]
	at peergos.server.sync.DirectorySync.mfa(DirectorySync.java:148)
	at peergos.server.sync.DirectorySync.lambda$init$3(DirectorySync.java:117)
	at peergos.shared.user.UserContext.lambda$getLoginData$17(UserContext.java:222)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 8 more
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.IllegalStateException: No supported 2 factor auth method! [MultiFactorAuthMethod{uid='13f008b8b1384682a5b2344840c2bda5', type=WEBAUTHN, enabled=true}]
	at peergos.server.sync.DirectorySync.init(DirectorySync.java:141)
	at peergos.server.Command.main(Command.java:75)
	at peergos.server.Command.main(Command.java:63)
	at peergos.server.Command.main(Command.java:63)
	at peergos.server.Main.main(Main.java:982)
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.IllegalStateException: No supported 2 factor auth method! [MultiFactorAuthMethod{uid='13f008b8b1384682a5b2344840c2bda5', type=WEBAUTHN, enabled=true}]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:994)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: No supported 2 factor auth method! [MultiFactorAuthMethod{uid='13f008b8b1384682a5b2344840c2bda5', type=WEBAUTHN, enabled=true}]
	at peergos.shared.util.Futures.logAndThrow(Futures.java:176)
	at peergos.shared.util.Futures.logAndThrow(Futures.java:169)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	... 9 more
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: No supported 2 factor auth method! [MultiFactorAuthMethod{uid='13f008b8b1384682a5b2344840c2bda5', type=WEBAUTHN, enabled=true}]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	... 8 more
Caused by: java.lang.IllegalStateException: No supported 2 factor auth method! [MultiFactorAuthMethod{uid='13f008b8b1384682a5b2344840c2bda5', type=WEBAUTHN, enabled=true}]
	at peergos.server.sync.DirectorySync.mfa(DirectorySync.java:148)
	at peergos.server.sync.DirectorySync.lambda$init$3(DirectorySync.java:117)
	at peergos.shared.user.UserContext.lambda$getLoginData$17(UserContext.java:222)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 8 more
```

**Comment by ianopolous** [comment]
We don't support webauthn on the CLI because it's designed for the web and would be very complicated to include support for.

**Comment by rapenne-s** [comment]
> We don't support webauthn on the CLI because it's designed for the web and would be very complicated to include support for.

This was my guess, however an proper error message should handle this case then as there is nothing to fix
