### ISSUE TITLE
Fix sql usage store errors

### ISSUE THREAD

**Issue by ianopolous** [Peergos/Peergos#660]
WARNING: ERROR: integer out of range
org.postgresql.util.PSQLException: ERROR: integer out of range
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at peergos.server.space.JdbcUsageStore.confirmUsage(JdbcUsageStore.java:98)
        at peergos.server.space.SpaceCheckingKeyFilter.processMutablePointerEvent(SpaceCheckingKeyFilter.java:249)
        at peergos.server.space.SpaceCheckingKeyFilter.processMutablePointerEvent(SpaceCheckingKeyFilter.java:206)
        at peergos.server.space.SpaceCheckingKeyFilter.lambda$new$0(SpaceCheckingKeyFilter.java:56)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ianopolous** [comment]
org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.execute(DB.java:854)
	at org.sqlite.core.DB.executeUpdate(DB.java:895)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at peergos.server.space.JdbcUsageStore.addWriter(JdbcUsageStore.java:210)
	at peergos.server.space.SpaceCheckingKeyFilter.processMutablePointerEvent(SpaceCheckingKeyFilter.java:247)
	at peergos.server.space.SpaceCheckingKeyFilter.processMutablePointerEvent(SpaceCheckingKeyFilter.java:206)
