### ISSUE TITLE
Fix S3 errors

### ISSUE THREAD

**Issue by ianopolous** [Peergos/Peergos#661]
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: null;
 S3 Extended Request ID: null), S3 Extended Request ID: null
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1742)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1371)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1347)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998)
        at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:394)
        at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:5940)
        at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1808)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1768)
        at peergos.server.storage.S3BlockStorage.put(S3BlockStorage.java:295)
        ... 30 more

**Comment by ianopolous** [comment]
Linode have said they are rate limiting us. We're well under the 750 req/s, at ~10 req/s. But we send ~40 around the same time and they are applying the rate limit at too small a granularity.

**Comment by ianopolous** [comment]
It turns out IPFS is DOSsing S3 with HEAD requests (700+ req/s). I've tried changing the bloom filter size from 0 to 256MiB to fix this.
