### ISSUE TITLE
migrate user

### ISSUE THREAD

**Issue by hu12305204** [Peergos/Peergos#825]
java -jar server/Peergos.jar migrate  -peergos-url https://beta.peergos.net
Move a Peergos account to this server.
Caused by: java.lang.RuntimeException: Server returned HTTP response code: 502 for URL: http://192.168.10.0:8080/p2p/QmcoDbhCiVXGrWs6rwBvB59Gm44veo7Qxn2zmRnPw7BaCH/http/peergos/v0/storage/usage?owner=z59vuwzfFDomuVEjWBXVQNokvZjqGtGkt4Quoss4u8ypDjHaCFk5eJ
         at peergos.shared.user.JavaPoster.post(JavaPoster.java:76)
        at peergos.shared.user.JavaPoster.post(JavaPoster.java:43)
        at peergos.shared.user.JavaPoster.postUnzip(JavaPoster.java:38)
        at peergos.shared.corenode.HTTPCoreNode.migrateUser(HTTPCoreNode.java:211)
        ... 5 more

what can i do with it?

**Comment by ianopolous** [comment]
Which user were you trying to migrate from the beta server?

**Comment by hu12305204** [comment]
I want to try the migrate the user 'hu12305024' 

> Which user were you trying to migrate from the beta server?

**Comment by ianopolous** [comment]
The peergos-url arg is the url of the server you want to migrate to (in this case http://localhost:8000) which must already be running.

**Comment by hu12305204** [comment]
[exec] Generating signup token...
[exec] Peergos daemon started. Browse to http://localhost:8000/?signup=true&token=7223c124ae026711cbbfe0f03d7283167c6d83a4c2d83fcd5582d690f6c0cd31 to sign up.
[exec] Running version 0.4.0-
the server is running  the result is the same

**Comment by ianopolous** [comment]
I'm going to look into this and try and reproduce, but it will take a little time as I'm flat out at the moment.

**Comment by ianopolous** [comment]
Can you show me the full command you are running?

**Comment by ianopolous** [comment]
My guess is that you are running the original command you used. The command needs to be,
> java -jar server/Peergos.jar migrate -peergos-url http://localhost:8000
