### ISSUE TITLE
how?

### ISSUE THREAD

**Issue by Monsterxi** [Peergos/Peergos#849]
Couldn't load native crypto library at /home/mrxi/native-lib/libtweetnacl.so, using pure Java version...
To use the native linux-x86-64 crypto implementation use option -Djava.library.path=native-lib

what do I need to do?
I tried build, but I still can't solve it.
I want to translate peergos into Chinese. what should I do.

**Comment by ianopolous** [comment]
That message just means you won't be using the native crypto implementation (which is Linux only), but that's fine. 

We don't have the resources to support internationalisation at the moment.

**Comment by Monsterxi** [comment]
thank you.

But I'm running java -jar Peergos.jar daemon -pki-node-id QmdM1TrjBJnYzzESATtrrMNPAtjJdqfcV2vF1kM39DY7cc -peergos.identity.hash z59vuwzfFDoqvC6R5QBV4tXtx2VK3Syvchsole

But an error was reported, I run  java -jar Peergos.jar daemon                           

Couldn't load native crypto library at /root/native-lib/native-lib/libtweetnacl.so, using pure Java version...
To use the native linux-x86-64 crypto implementation use option -Djava.library.path=native-lib
Looking up OS: linux
Looking up architecture: amd64

It's not running properly

If possible, please provide detailed self-hosted documentation



7月 22, 2021 1:57:40 下午 peergos.server.storage.IpfsInstaller ensureInstalled
信息: ipfs-exe /root/.peergos/ipfs not available
7月 22, 2021 1:57:40 下午 peergos.server.storage.IpfsInstaller install
信息: Downloading ipfs binary https://github.com/peergos/ipfs-releases/blob/master/v0.9.0/linux-amd64/ipfs?raw=true...
7月 22, 2021 1:57:44 下午 peergos.server.util.Logging lambda$init$0
严重: Uncaught Exception in thread 1:main
java.lang.RuntimeException: java.lang.RuntimeException: java.net.ConnectException: 拒绝连接 (Connection refused)
	at peergos.server.Main.startPeergos(Main.java:590)
	at peergos.server.Command.main(Command.java:75)
	at peergos.server.Command.main(Command.java:63)
	at peergos.server.Main.main(Main.java:742)
Caused by: java.lang.RuntimeException: java.net.ConnectException: 拒绝连接 (Connection refused)
	at peergos.server.storage.IpfsInstaller.install(IpfsInstaller.java:323)
	at peergos.server.storage.IpfsInstaller.ensureInstalled(IpfsInstaller.java:270)
	at peergos.server.storage.IpfsInstaller.ensureInstalled(IpfsInstaller.java:178)
	at peergos.server.Main.lambda$static$0(Main.java:65)
	at peergos.server.Command.main(Command.java:75)
	at peergos.server.Main.startPeergos(Main.java:417)
	... 3 more
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:240)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2783)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2695)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at peergos.server.storage.IpfsInstaller.install(IpfsInstaller.java:299)
	... 8 more

7月 22, 2021 2:01:22 下午 peergos.server.storage.IpfsInstaller ensureInstalled
信息: ipfs-exe /root/.peergos/ipfs not available
7月 22, 2021 2:01:22 下午 peergos.server.storage.IpfsInstaller install
信息: Downloading ipfs binary https://github.com/peergos/ipfs-releases/blob/master/v0.9.0/linux-amd64/ipfs?raw=true...
7月 22, 2021 2:01:24 下午 peergos.server.util.Logging lambda$init$0
严重: Uncaught Exception in thread 1:main
java.lang.RuntimeException: javax.net.ssl.SSLException: Connection reset
	at peergos.server.storage.IpfsInstaller.install(IpfsInstaller.java:323)
	at peergos.server.storage.IpfsInstaller.ensureInstalled(IpfsInstaller.java:270)
	at peergos.server.storage.IpfsInstaller.ensureInstalled(IpfsInstaller.java:178)
	at peergos.server.Main.lambda$static$0(Main.java:65)
	at peergos.server.Command.main(Command.java:75)
	at peergos.server.Main.lambda$static$1(Main.java:107)
	at peergos.server.Command.main(Command.java:75)
	at peergos.server.Command.main(Command.java:63)
	at peergos.server.Main.main(Main.java:742)
Caused by: javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:144)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at peergos.server.storage.IpfsInstaller.install(IpfsInstaller.java:299)
	... 8 more
	Suppressed: java.net.SocketException: 断开的管道 (Write failed)
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:380)
		... 22 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	... 19 more

7月 22, 2021 2:01:49 下午 peergos.server.storage.IpfsInstaller ensureInstalled
信息: ipfs-exe /root/.peergos/ipfs not available
7月 22, 2021 2:01:49 下午 peergos.server.storage.IpfsInstaller install
信息: Downloading ipfs binary https://github.com/peergos/ipfs-releases/blob/master/v0.9.0/linux-amd64/ipfs?raw=true...
7月 22, 2021 2:01:52 下午 peergos.server.util.Logging lambda$init$0
严重: Uncaught Exception in thread 1:main
java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: Connection reset
	at peergos.server.Main.startPeergos(Main.java:590)
	at peergos.server.Command.main(Command.java:75)
	at peergos.server.Command.main(Command.java:63)
	at peergos.server.Main.main(Main.java:742)
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLException: Connection reset
	at peergos.server.storage.IpfsInstaller.install(IpfsInstaller.java:323)
	at peergos.server.storage.IpfsInstaller.ensureInstalled(IpfsInstaller.java:270)
	at peergos.server.storage.IpfsInstaller.ensureInstalled(IpfsInstaller.java:178)
	at peergos.server.Main.lambda$static$0(Main.java:65)
	at peergos.server.Command.main(Command.java:75)
	at peergos.server.Main.startPeergos(Main.java:417)
	... 3 more
Caused by: javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:144)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2783)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2695)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at peergos.server.storage.IpfsInstaller.install(IpfsInstaller.java:299)
	... 8 more
	Suppressed: java.net.SocketException: 断开的管道 (Write failed)
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:380)
		... 24 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	... 21 more

7月 22, 2021 2:03:16 下午 peergos.server.storage.IpfsInstaller ensureInstalled
信息: ipfs-exe /root/.peergos/ipfs not available
7月 22, 2021 2:03:17 下午 peergos.server.storage.IpfsInstaller install
信息: Downloading ipfs binary https://github.com/peergos/ipfs-releases/blob/master/v0.9.0/linux-amd64/ipfs?raw=true...
7月 22, 2021 2:07:05 下午 peergos.server.storage.IpfsInstaller ensureInstalled
信息: ipfs-exe /root/.peergos/ipfs not available
7月 22, 2021 2:07:05 下午 peergos.server.storage.IpfsInstaller install
信息: Downloading ipfs binary https://github.com/peergos/ipfs-releases/blob/master/v0.9.0/linux-amd64/ipfs?raw=true...
7月 22, 2021 2:07:08 下午 peergos.server.util.Logging lambda$init$0
严重: Uncaught Exception in thread 1:main
java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: Connection reset
	at peergos.server.Main.startPeergos(Main.java:590)
	at peergos.server.Command.main(Command.java:75)
	at peergos.server.Command.main(Command.java:63)
	at peergos.server.Main.main(Main.java:742)
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLException: Connection reset
	at peergos.server.storage.IpfsInstaller.install(IpfsInstaller.java:323)
	at peergos.server.storage.IpfsInstaller.ensureInstalled(IpfsInstaller.java:270)
	at peergos.server.storage.IpfsInstaller.ensureInstalled(IpfsInstaller.java:178)
	at peergos.server.Main.lambda$static$0(Main.java:65)
	at peergos.server.Command.main(Command.java:75)
	at peergos.

**Comment by gyurmogyuri** [comment]
I have same on arm64.
