### ISSUE TITLE
How to run in local?

### ISSUE THREAD

**Issue by Nafidinara** [Peergos/Peergos#914]
hello Im new here, how to run in properly in my local, I've lack information about this, what requirement that I need to run it, when I run, Im get this error : 
`java -jar Peergos.jar daemon -log-to-console true
Couldn't load native crypto library at , using pure Java version...
To use the native linux-x86-64 crypto implementation use option -Djava.library.path=native-lib
Mar 28, 2022 8:49:43 AM peergos.server.util.Logging init
INFO: Logging to C:\Users\asus\.peergos\peergos.0.log
Looking up OS: windows 10
Looking up architecture: amd64
Connection refused: connect retrieving api/v0/id
Mar 28, 2022 8:49:47 AM peergos.server.storage.IpfsWrapper build
INFO: Using IPFS dir C:\Users\asus\.peergos\.ipfs and IPFS binary C:\Users\asus\.peergos\ipfs.exe
Mar 28, 2022 8:49:47 AM peergos.server.storage.IpfsWrapper configure
INFO: Setting ipfs bootstrap nodes [/ip4/172.104.157.121/tcp/4001/ipfs/QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF, /ip6/2a01:7e01:0:0:f03c:92ff:fe26:f671/tcp/4001/ipfs/QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF, /ip4/172.104.143.23/tcp/4001/ipfs/QmcoDbhCiVXGrWs6rwBvB59Gm44veo7Qxn2zmRnPw7BaCH, /ip6/2a01:7e01:0:0:f03c:92ff:fee5:154a/tcp/4001/ipfs/QmcoDbhCiVXGrWs6rwBvB59Gm44veo7Qxn2zmRnPw7BaCH, /dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN, /dnsaddr/bootstrap.libp2p.io/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa, /dnsaddr/bootstrap.libp2p.io/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb, /dnsaddr/bootstrap.libp2p.io/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt, /ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ, /ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM, /ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu, /ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64, /ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd, /ip6/2604:a880:1:20:0:0:203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM, /ip6/2400:6180:0:d0:0:0:151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu, /ip6/2604:a880:800:10:0:0:4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64, /ip6/2a03:b0c0:0:1010:0:0:23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd, /ip4/104.131.131.82/udp/4001/quic/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ]
config --json Bootstrap [\"/ip4/172.104.157.121/tcp/4001/ipfs/QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF\",\"/ip6/2a01:7e01:0:0:f03c:92ff:fe26:f671/tcp/4001/ipfs/QmVdFZgHnEgcedCS2G2ZNiEN59LuVrnRm7z3yXtEBv2XiF\",\"/ip4/172.104.143.23/tcp/4001/ipfs/QmcoDbhCiVXGrWs6rwBvB59Gm44veo7Qxn2zmRnPw7BaCH\",\"/ip6/2a01:7e01:0:0:f03c:92ff:fee5:154a/tcp/4001/ipfs/QmcoDbhCiVXGrWs6rwBvB59Gm44veo7Qxn2zmRnPw7BaCH\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb\",\"/dnsaddr/bootstrap.libp2p.io/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt\",\"/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ\",\"/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM\",\"/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu\",\"/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64\",\"/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd\",\"/ip6/2604:a880:1:20:0:0:203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM\",\"/ip6/2400:6180:0:d0:0:0:151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu\",\"/ip6/2604:a880:800:10:0:0:4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64\",\"/ip6/2a03:b0c0:0:1010:0:0:23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd\",\"/ip4/104.131.131.82/udp/4001/quic/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ\"]
config Addresses.ProxyTarget /ip4/127.0.0.1/tcp/8003
Mar 28, 2022 8:49:47 AM peergos.server.storage.IpfsWrapper configure
INFO: Running ipfs config
config --json Experimental.Libp2pStreamMounting true
config --json Experimental.P2pHttpProxy true
config Addresses.API /ip4/127.0.0.1/tcp/5001
config Addresses.Gateway /ip4/127.0.0.1/tcp/8080
config Addresses.AllowTarget http://127.0.0.1:8002
config --json Addresses.Swarm [\"/ip4/0.0.0.0/tcp/4001\",\"/ip6/::/tcp/4001\"]
Mar 28, 2022 8:49:48 AM peergos.server.storage.IpfsWrapper start
INFO: Starting ipfs daemon
daemon
Connection refused: connect retrieving api/v0/id
Mar 28, 2022 8:49:53 AM peergos.server.util.Logging log
INFO: $(ipfs daemon) out: Fatal error  listen tcp 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Mar 28, 2022 8:49:53 AM peergos.server.storage.IpfsWrapper run
WARNING: IPFS exited with return-code 1
Mar 28, 2022 8:49:54 AM peergos.server.storage.IpfsWrapper start
INFO: Starting ipfs daemon
daemon
Connection refused: connect retrieving api/v0/id
Mar 28, 2022 8:49:59 AM peergos.server.util.Logging log
INFO: $(ipfs daemon) out: Fatal error  listen tcp 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Mar 28, 2022 8:49:59 AM peergos.server.storage.IpfsWrapper run
WARNING: IPFS exited with return-code 1
Mar 28, 2022 8:50:00 AM peergos.server.storage.IpfsWrapper start
INFO: Starting ipfs daemon
daemon
Connection refused: connect retrieving api/v0/id
Mar 28, 2022 8:50:05 AM peergos.server.util.Logging log
INFO: $(ipfs daemon) out: Fatal error  listen tcp 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Mar 28, 2022 8:50:05 AM peergos.server.storage.IpfsWrapper run
WARNING: IPFS exited with return-code 1
Mar 28, 2022 8:50:06 AM peergos.server.storage.IpfsWrapper start
INFO: Starting ipfs daemon
daemon
Connection refused: connect retrieving api/v0/id
Mar 28, 2022 8:50:11 AM peergos.server.util.Logging log
INFO: $(ipfs daemon) out: Fatal error  listen tcp 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Mar 28, 2022 8:50:11 AM peergos.server.storage.IpfsWrapper run
WARNING: IPFS exited with return-code 1
Connection refused: connect retrieving api/v0/id
Mar 28, 2022 8:50:12 AM peergos.server.storage.IpfsWrapper start
INFO: Starting ipfs daemon
daemon
Connection refused: connect retrieving api/v0/id
Mar 28, 2022 8:50:18 AM peergos.server.util.Logging log
INFO: $(ipfs daemon) out: Fatal error  listen tcp 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Mar 28, 2022 8:50:18 AM peergos.server.storage.IpfsWrapper run
WARNING: IPFS exited with return-code 1
Mar 28, 2022 8:50:18 AM peergos.server.util.Logging lambda$init$0
SEVERE: Uncaught Exception in thread 1:main
java.lang.RuntimeException: java.lang.IllegalStateException: ipfs daemon is not ready after specified timeout 30 seconds.
        at peergos.server.Main.startPeergos(Main.java:725)
        at peergos.server.Command.main(Command.java:75)
        at peergos.server.Command.main(Command.java:63)
        at peergos.server.Main.main(Main.java:880)
Caused by: java.lang.IllegalStateException: ipfs daemon is not ready after specified timeout 30 seconds.
        at peergos.server.storage.IpfsWrapper.waitForDaemon(IpfsWrapper.java:196)
        at peergos.server.storage.IpfsWrapper.launchAndManage(IpfsWrapper.java:455)
        at peergos.server.Main.startIpfs(Main.java:796)
        at peergos.server.Command.main(Command.java:75)
        at peergos.server.Main.startPeergos(Main.java:512)
        ... 3 more

Mar 28, 2022 8:50:19 AM peergos.server.storage.IpfsWrapper start
INFO: Starting ipfs daemon
daemon
Mar 28, 2022 8:50:24 AM peergos.server.util.Logging log
INFO: $(ipfs daemon) out: Fatal error  listen tcp 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Mar 28, 2022 8:50:24 AM peergos.server.storage.IpfsWrapper run
WARNING: IPFS exited with return-code 1
Mar 28, 2022 8:50:25 AM peergos.server.storage.IpfsWrapper start
INFO: Starting ipfs daemon
daemon
Mar 28, 2022 8:50:30 AM peergos.server.util.Logging log
INFO: $(ipfs daemon) out: Fatal error  listen tcp 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Mar 28, 2022 8:50:30 AM peergos.server.storage.IpfsWrapper run
WARNING: IPFS exited with return-code 1
Mar 28, 2022 8:50:31 AM peergos.server.storage.IpfsWrapper start
INFO: Starting ipfs daemon
daemon
Mar 28, 2022 8:50:36 AM peergos.server.util.Logging log
INFO: $(ipfs daemon) out: Fatal error  listen tcp 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Mar 28, 2022 8:50:36 AM peergos.server.storage.IpfsWrapper run
WARNING: IPFS exited with return-code 1
Mar 28, 2022 8:50:37 AM peergos.server.storage.IpfsWrapper start
INFO: Starting ipfs daemon`

**Comment by ianopolous** [comment]
It looks like it's unable to listen on localhost:8080. It seems like your Windows is blocking listening on that port. You can check by following: https://ardalis.com/attempt-made-to-access-socket/

To change that port, use the arg -ipfs-gateway-address /ip4/127.0.0.1/tcp/8080 with a different port value

**Comment by jonaswre** [comment]
I've been having socket issuse lately (in general not with peergos).
For me restarting winnat solves it. But it will be broken after each restart. 
I think some windows updated messed something up 
`net stop winnat
net start winnat`

**Comment by aereaco** [comment]
Where can the Peergos.jar file be found?

**Comment by ianopolous** [comment]
The latest jar is built in the web-ui repo:
https://github.com/Peergos/web-ui/suites/9347681002/artifacts/439748693
Normally it is available at https://peergos.net/public/peergos/releases but we are about to do a release and I would recommend either waiting for that, or using the build link above.
