### ISSUE TITLE
Unauthorized! Error

### ISSUE THREAD

**Issue by DillFrescott** [Peergos/Peergos#924]
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unauthorised!
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at peergos.server.storage.AuthedStorage.getRaw(AuthedStorage.java:58)
        at peergos.server.storage.AuthedStorage.getRaw(AuthedStorage.java:54)
        at peergos.server.storage.AuthedStorage.get(AuthedStorage.java:44)
        at peergos.server.storage.DeletableContentAddressedStorage.lambda$get$0(DeletableContentAddressedStorage.java:50)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.server.storage.DeletableContentAddressedStorage.get(DeletableContentAddressedStorage.java:50)
        at peergos.server.storage.AuthedStorage.get(AuthedStorage.java:39)
        at peergos.server.storage.AuthedCachingStorage.get(AuthedCachingStorage.java:107)
        at peergos.shared.storage.DelegatingStorage.get(DelegatingStorage.java:54)
        at peergos.shared.storage.ContentAddressedStorage$Proxying.get(ContentAddressedStorage.java:578)
        at peergos.server.storage.AuthedCachingStorage.get(AuthedCachingStorage.java:107)
        at peergos.server.net.DHTHandler.handle(DHTHandler.java:211)
        at peergos.server.net.SubdomainHandler.handle(SubdomainHandler.java:28)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:733)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Unauthorised!
        at peergos.server.storage.AuthedStorage.lambda$getRaw$1(AuthedStorage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
        ... 25 more
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unauthorised!
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at peergos.server.storage.AuthedStorage.getRaw(AuthedStorage.java:58)
        at peergos.server.storage.AuthedStorage.getRaw(AuthedStorage.java:54)
        at peergos.server.storage.AuthedStorage.get(AuthedStorage.java:44)
        at peergos.server.storage.DeletableContentAddressedStorage.lambda$get$0(DeletableContentAddressedStorage.java:50)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.server.storage.DeletableContentAddressedStorage.get(DeletableContentAddressedStorage.java:50)
        at peergos.server.storage.AuthedStorage.get(AuthedStorage.java:39)
        at peergos.server.storage.AuthedCachingStorage.get(AuthedCachingStorage.java:107)
        at peergos.shared.storage.DelegatingStorage.get(DelegatingStorage.java:54)
        at peergos.shared.storage.ContentAddressedStorage$Proxying.get(ContentAddressedStorage.java:578)
        at peergos.server.storage.AuthedCachingStorage.get(AuthedCachingStorage.java:107)
        at peergos.server.net.DHTHandler.handle(DHTHandler.java:211)
        at peergos.server.net.SubdomainHandler.handle(SubdomainHandler.java:28)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:733)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Unauthorised!
        at peergos.server.storage.AuthedStorage.lambda$getRaw$1(AuthedStorage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
        ... 25 more
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unauthorised!
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at peergos.server.storage.AuthedStorage.getRaw(AuthedStorage.java:58)
        at peergos.server.storage.AuthedStorage.getRaw(AuthedStorage.java:54)
        at peergos.server.storage.AuthedStorage.get(AuthedStorage.java:44)
        at peergos.server.storage.DeletableContentAddressedStorage.lambda$get$0(DeletableContentAddressedStorage.java:50)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.server.storage.DeletableContentAddressedStorage.get(DeletableContentAddressedStorage.java:50)
        at peergos.server.storage.AuthedStorage.get(AuthedStorage.java:39)
        at peergos.server.storage.AuthedCachingStorage.get(AuthedCachingStorage.java:107)
        at peergos.shared.storage.DelegatingStorage.get(DelegatingStorage.java:54)
        at peergos.shared.storage.ContentAddressedStorage$Proxying.get(ContentAddressedStorage.java:578)
        at peergos.server.storage.AuthedCachingStorage.get(AuthedCachingStorage.java:107)
        at peergos.server.net.DHTHandler.handle(DHTHandler.java:211)
        at peergos.server.net.SubdomainHandler.handle(SubdomainHandler.java:28)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:733)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Unauthorised!
        at peergos.server.storage.AuthedStorage.lambda$getRaw$1(AuthedStorage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
        ... 25 more

**Comment by ianopolous** [comment]
Have you got some context? What were you doing at the time?

**Comment by DillFrescott** [comment]
Sorry. I'm trying to self host peergos. I ran the `java -jar Peergos.jar daemon -generate-token true` command on the Peergos.jar file and it gave me a signup link with a token. So i clicked sign up and it just throws an error and says cant retrieve entry point and thats what it says in console...

**Comment by ianopolous** [comment]
One other user has also reported this but I haven't been able to reproduce it. What OS/browser this?

**Comment by DillFrescott** [comment]
It's the Brave Browser

**Comment by jahanson** [comment]
Checking in here, same issue on Ubuntu 20.04

**Comment by ianopolous** [comment]
Thanks to @jahanson I now understand what's going on here, and will have a fix soon.
