### ISSUE TITLE
How to use fuse mount on Windows

### ISSUE THREAD

**Issue by jonaswre** [Peergos/Peergos#932]
I've downloaded the binary. And ./peergos.exe fuse -username "myusername" -password "mypassword"

But I always get "Connection refused: connect retrieving peergos/v0/core/getUsernamesGzip/" 

Do I need to specify webport and mountPoint?

**Comment by ianopolous** [comment]
Yes the fuse command assumes a Peergos daemon is already running locally. The FUSE integration hasn't been tested on Windows so do let us know how you get on.

**Comment by jonaswre** [comment]
Thanks for the info. 

I now get the error 

> Apr 18, 2022 5:45:13 PM jnr.ffi.util.ref.internal.Finalizer getInheritableThreadLocalsField INFO: Couldn't access Thread.inheritableThreadLocals. Reference finalizer threads will inherit thread local values.

 in the fuse mount bash and 

> java.util.concurrent.CompletionException: java.net.SocketTimeoutException: Read timed out
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at peergos.shared.storage.ContentAddressedStorageProxy$HTTP.getChampLookup(ContentAddressedStorageProxy.java:100)
        at peergos.shared.storage.ContentAddressedStorage$Proxying.lambda$getChampLookup$5(ContentAddressedStorage.java:573)
        at peergos.shared.corenode.Proxy.lambda$redirectCall$0(Proxy.java:28)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.corenode.Proxy.lambda$redirectCall$1(Proxy.java:19)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.corenode.Proxy.redirectCall(Proxy.java:18)
        at peergos.shared.storage.ContentAddressedStorage$Proxying.getChampLookup(ContentAddressedStorage.java:569)
        at peergos.shared.storage.DelegatingStorage.getChampLookup(DelegatingStorage.java:79)
        at peergos.server.net.DHTHandler.handle(DHTHandler.java:128)
        at peergos.server.net.SubdomainHandler.handle(SubdomainHandler.java:28)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:733)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:69)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:44)
        at peergos.shared.user.HttpPoster.post(HttpPoster.java:11)
        at peergos.server.util.JavaPoster.postUnzip(JavaPoster.java:39)
        at peergos.shared.user.HttpPoster.postUnzip(HttpPoster.java:17)
        at peergos.server.util.JavaPoster.get(JavaPoster.java:155)
        at peergos.server.util.JavaPoster.get(JavaPoster.java:144)
        at peergos.shared.storage.ContentAddressedStorageProxy$HTTP.getChampLookup(ContentAddressedStorageProxy.java:95)
        ... 21 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:791)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3221)
        at java.base/java.net.URLConnection.getContentEncoding(URLConnection.java:531)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:67)

on the deamon. 

I'm using the jar file now instead of the binary. (The binary wouldn't start the daemon)

I tried the fuse mount as admin and non admin. 

Thanks

**Comment by ianopolous** [comment]
Ok, we've been meaning to update the fuse library we use for a while (it's quite out of date, so that's probably our first port of call, but they've changed their APIs so it's a bit of work).

**Comment by jonaswre** [comment]
No worries i'll just boot my linux for the initial data transfer.

**Comment by jonaswre** [comment]
Im now using the latest relaese. 

But I still get errors. At first I only got

> Peergos mounted at peergos

And then the progress stops. After checking the logs i realised winfs was missing. (Maybe that could be in the console output not just as error in the logs?) 

I now get the error

> Cannot create WinFsp-FUSE file system: mount point in use.
> Apr 21, 2022 9:23:00 PM peergos.server.util.Logging lambda$init$0
> SEVERE: Uncaught Exception in thread 1:main
> java.lang.IllegalStateException: ru.serce.jnrfuse.FuseException: Unable to mount FS
>         at peergos.server.Main.startFuse(Main.java:798)
>         at peergos.server.Command.main(Command.java:75)
>         at peergos.server.Command.main(Command.java:63)
>         at peergos.server.Main.main(Main.java:902)
> Caused by: ru.serce.jnrfuse.FuseException: Unable to mount FS
>         at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:281)
>         at peergos.server.fuse.FuseProcess.start(FuseProcess.java:42)
>         at peergos.server.Main.startFuse(Main.java:795)
>         ... 3 more
> Caused by: ru.serce.jnrfuse.FuseException: Unable to mount FS, return code = 1
>         at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:277)
>         ... 5 more

I can confirm the folder was created by the process it should be in use because it was created by the process. 


Antivirus is not the issuse I tried with it turned off.
Any idea what to do?

**Comment by ianopolous** [comment]
The fuse lib's windows instructions say something about a system property or installing winfsp? 
https://github.com/SerCeMan/jnr-fuse/blob/master/INSTALLATION.md
Sorry I'm not much help here.

Are you able to use the linux fuse binding in the window subsystem for linux?

**Comment by ianopolous** [comment]
Is the reason for using FUSE to import all your data initially without using a browser? If so we may have another solution - the shell command, which is likely faster than fuse as well. However it doesn't currently support uploading entire directories. If this interests you, I can work on adding that (which shouldn't be too hard).

**Comment by jonaswre** [comment]
Yes thats the reason. When I try to upload 100+GB using the browser. Everytime i come back to my pc to check the progress I got logged out and files will only be added to the directory if all files were added successfully. Thats the reason I wanted to use fuse.

**Comment by ianopolous** [comment]
Ok I'll add folder upload to the shell command asap.

**Comment by jonaswre** [comment]
Can i upload multiple files at once? Not the whole folder but all files in the folder?
Whats the comment i would use? I can just write a bash and loop through while you implement folder upload

**Comment by ianopolous** [comment]
At the moment shell only does 1 file per command, but I'll implement folder upload. Because you need to login it's not really externally scriptable. You can try it out in the meantime to see the available commands. 
> java -jar Peergos.jar shell

**Comment by ianopolous** [comment]
Ok I've implemented it, I will cut a new release once it's merged and comment again here.

**Comment by ianopolous** [comment]
I've cut a new release with folder upload in the shell CLI: https://github.com/Peergos/web-ui/releases/tag/v0.9.1

**Comment by jonaswre** [comment]
Could you provide a quick example java -jar Peergos.jar shell --help shows no output

**Comment by ianopolous** [comment]
No args are necessary, it will ask you for the serer address username and password at startup. For example:
> java -jar Peergos.jar shell
Enter Server address
> \> https://peergos.net
> Enter username
> \> demo
> Enter password for 'demo'
> \> **************************************
>Generating keys
>Logging in
>Retrieving Friends
> demo@https://peergos.net > 

Then if you type help you see the available shell commands
> demo@https://peergos.net >help
> Available commands:
> help                                                                        	Show this help.
> exit                                                                        	Disconnect.
> get remote-path <local path>                                                	Download a file.
> put local-path <remote-path>                                                	Upload a file.
> ls <path>                                                                   	List contents of a remote directory.
> rm remote-path                                                              	Remove a remote-file.
> space                                                                       	Show used remote space.
> get_follow_requests                                                         	Show the users that have sent you a follow request.
> process_follow_request pending-follower accept|accept-and-reciprocate|reject	Accept or reject a pending follow-request.
> follow user                                                                 	Send a follow-request to another user.
> share_read remote-path user                                                 	Grant read access for a file to another user.
> passwd                                                                      	Update your password.
> cd remote-path                                                              	change (remote) directory.
> pwd                                                                         	Print (remote) working directory.
> lpwd                                                                        	Print (local) working directory.
> quit                                                                        	Disconnect.
> bye                                                                         	Disconnect.
> 
> Note: <TAB> based autocomplete is available on most commands.
> demo@https://peergos.net >

**Comment by ianopolous** [comment]
github's mangled the formatting there, but it's clearer on the CLI.
To upload a folder you want:
put $local_path $remote_path

**Comment by jonaswre** [comment]
Thank you very much. Maybe add that to the github readme?

**Comment by jonaswre** [comment]
Oh and I think this way to provide credentails is way better then to provide it by argument because this way the password wont be in bash_history

**Comment by ianopolous** [comment]
Yep, 100% agree on the bash history. I'll update fuse to do that too, or maybe accept an environment var

**Comment by jonaswre** [comment]
```
/       [====================]  java.util.concurrent.CompletionException: java.lang.IllegalStateException: File already exists with name -1487873678
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1194)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFileSection$137(FileWrapper.java:1083)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFileSection$138(FileWrapper.java:1082)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.uploadFileSection(FileWrapper.java:1081)
        at peergos.shared.user.fs.FileWrapper.uploadFileSection(FileWrapper.java:1046)
        at peergos.shared.user.fs.transaction.TransactionServiceImpl.lambda$open$1(TransactionServiceImpl.java:51)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.transaction.TransactionServiceImpl.open(TransactionServiceImpl.java:50)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFolder$89(FileWrapper.java:797)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFolder$90(FileWrapper.java:797)
        at peergos.shared.util.Futures.lambda$reduceAll$12(Futures.java:86)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at peergos.shared.storage.IpfsTransaction.lambda$call$0(IpfsTransaction.java:24)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at peergos.shared.storage.IpfsTransaction.lambda$call$1(IpfsTransaction.java:24)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalStateException: File already exists with name -1487873678
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFileSection$136(FileWrapper.java:1086)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        ... 44 more
java.util.concurrent.CompletionException: java.lang.IllegalStateException: File already exists with name -1487873678
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1194)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFileSection$137(FileWrapper.java:1083)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFileSection$138(FileWrapper.java:1082)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.uploadFileSection(FileWrapper.java:1081)
        at peergos.shared.user.fs.FileWrapper.uploadFileSection(FileWrapper.java:1046)
        at peergos.shared.user.fs.transaction.TransactionServiceImpl.lambda$open$1(TransactionServiceImpl.java:51)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.transaction.TransactionServiceImpl.open(TransactionServiceImpl.java:50)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFolder$89(FileWrapper.java:797)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFolder$90(FileWrapper.java:797)
        at peergos.shared.util.Futures.lambda$reduceAll$12(Futures.java:86)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at peergos.shared.storage.IpfsTransaction.lambda$call$0(IpfsTransaction.java:24)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at peergos.shared.storage.IpfsTransaction.lambda$call$1(IpfsTransaction.java:24)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalStateException: File already exists with name -1487873678
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFileSection$136(FileWrapper.java:1086)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        ... 44 more
```

I'm still having trouble uploading my folder. Its 130 GB and its always fails at some point. And the biggest problem is I don't know which file causes a problem because the folder is always empty (no file is uploaded or atleast I cant see it in the UI)

Im not sure how files are recognized as the same, but if I upload a folder into a clean peergos folder how can the file already exsits? 

The issue is present wsl and windows. But windows also has issues with reading instream. 

And put should have a option ether to override or skip just in general.

Why is it that I cant see any files in the folder im uploading to until all files where updatet?

**Comment by ianopolous** [comment]
Are you uploading using the shell with server address https://peergos.net?

Those are fileupload transaction files. For larger files we create a transaction file first which contains enough info to clean up the chunk if the upload fails. You can clear these using the web-ui by going to the user menu in the top right and selecting "cleanup failed uploads", though it will only cleanup failed uploads started more than a day ago. I'm actually working right now on resumable uploads which would handle this case by asking you if you want to continue the file upload or clear and reupload it. 

Bulk upload doesn't update the folder until all the children are uploaded, but this may change in the current work I'm doing.

**Comment by jonaswre** [comment]
I've tried both peergos.org and localhost both resulted in errors. So best would be to wait a day then cleanup all failed chunks and  try again?

**Comment by ianopolous** [comment]
Yep, until I finish the resumable uploads. Or I could do a minor release with a CLI cleanup script that lets you ignore the day delay if you prefer (it's only there so you don't delete an in progress file upload - so as long as you're not concurrently uploading it's safe). 

What were the errors you saw uploading?

**Comment by jonaswre** [comment]
If you could create a cli cleanup script, I could better test the errors. Is there enhanced logging? It might be usefull to the figure out if the same file always fails.

**Comment by jonaswre** [comment]
Cleanup in Browser seems to have issues too.

> Open file upload transactions: 9
> peergoslib.nocache.js:13988 Stale file upload transactions: 6
> peergoslib.nocache.js:13988 java.lang.JsException: Error: Network timeout
> peergoslib.nocache.js:13988 	at Unknown.req.ontimeout(https://peergos.net/js/vendor.js)
> peergos.js:1512 Error: Network timeout
> peergoslib.nocache.js:13988 Open file upload transactions: 7
> peergoslib.nocache.js:13988 Stale file upload transactions: 4

Im pretty sure its not an issue with my connection. Im only connected by wire. Ethernet at home and fiber to the isp.

**Comment by ianopolous** [comment]
Yes we'll be adding feedback and more options to the ui later, including letting you choose to cleanup an upload that only just failed. It sounds like you'll try out the upload again. Let me know how it goes here. I'll keep working on resumable uploads.

**Comment by jonaswre** [comment]
The error i get is

> -       [====================]  java.util.concurrent.CompletionException: java.lang.IllegalStateException: File already exists with name 1224666140
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1194)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFileSection$137(FileWrapper.java:1083)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFileSection$138(FileWrapper.java:1082)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.uploadFileSection(FileWrapper.java:1081)
        at peergos.shared.user.fs.FileWrapper.uploadFileSection(FileWrapper.java:1046)
        at peergos.shared.user.fs.transaction.TransactionServiceImpl.lambda$open$1(TransactionServiceImpl.java:51)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.transaction.TransactionServiceImpl.open(TransactionServiceImpl.java:50)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFolder$89(FileWrapper.java:797)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFolder$90(FileWrapper.java:797)
        at peergos.shared.util.Futures.lambda$reduceAll$12(Futures.java:86)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at peergos.shared.storage.IpfsTransaction.lambda$call$0(IpfsTransaction.java:24)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at peergos.shared.storage.IpfsTransaction.lambda$call$1(IpfsTransaction.java:24)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalStateException: File already exists with name 1224666140
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFileSection$136(FileWrapper.java:1086)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        ... 44 more
java.util.concurrent.CompletionException: java.lang.IllegalStateException: File already exists with name 1224666140
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1194)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.user.fs.FileWrapper.lambda$uploadFileSection$137(FileWrapper.java:1083)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)

I waited a day and cleaned up. 

> Open file upload transactions: 0
> peergoslib.nocache.js:13988 Stale file upload transactions: 0

**Comment by ianopolous** [comment]
Thank you. That's very odd. The numerical filename is the name of the upload transaction file and is computed as path.hashcode. Maybe you're hitting a hash collision between 2 files in a folder. I've almost finished upload resumption and this includes a rewrite of folder upload which I think will fix this as we close the upload transactions much sooner. I'll post here when it's released. I can also use a cryptographic hash for the transaction name and then there won't be any collisions.

**Comment by jonaswre** [comment]
I'll try and figure out if there is a collision. But I think if you do sha256(path) thats highly unlikley. Or do you do sha256(content) because 2 files might have the same content but the won't have the same path.

**Comment by ianopolous** [comment]
Currently it's not a cryptographic hash, so collisions are possible. I've already changed it to sha256 in the resume upload work now. This is in [PR](https://github.com/Peergos/Peergos/pull/947) already, we're just fixing a few issues before merging. It's hash(path) only. 

You are right that if there was a collision with sha256 then that would be front page news.

**Comment by ianopolous** [comment]
Resumable uploads is done. I've published a new release here:
https://github.com/Peergos/web-ui/releases/tag/v0.9.2

There's a new 3rd skip parameter on the CLI put command which will automatically resume failed uploads now. You can also resume via the web-ui which will ask you to confirm each resumption.

**Comment by jonaswre** [comment]
I've cleaned up failed uploads. And know its seems to work great. I can see the finshed files in the ui even if the whole upload didn't finish yet!

**Comment by ianopolous** [comment]
Excellent! Yes that was another change we made so the current dir is refreshed every 10 MiB of upload or every file for large files.
