### ISSUE TITLE
Mobile apps

### ISSUE THREAD

**Issue by ianopolous** [Peergos/Peergos#978]
Build android and iOS apps.

Initially just using existing webui in a webview.

**Comment by jonaswre** [comment]
Are you still thinking flutter, react native or Ionic?

**Comment by ianopolous** [comment]
Not sure yet, but if we can get something working with minimal code changes then that might be a start.

**Comment by jonaswre** [comment]
Why not progressive web App if least changes is the goal? What's the use exact case?

**Comment by ianopolous** [comment]
PWAs aren't support by some major browsers/OSes. That doesn't mean we can't do it as well though. With a native app we can gradually add things like local storage easily and in a way that the browser won't randomly delete it.

**Comment by ianopolous** [comment]
The thing I'm looking into to try and get it running quickly is gluon (JavaFX)

**Comment by ianopolous** [comment]
I've got a super minimal version (just a webview loading peergos.net) working for android, and supposedly for iOS, but I can't test that - https://github.com/peergos/mobile

**Comment by jonaswre** [comment]
> I've got a super minimal version (just a webview loading peergos.net) working for android, and supposedly for iOS, but I can't test that - https://github.com/peergos/mobile

I've got a mac and a dev account so I could test it. 


> The thing I'm looking into to try and get it running quickly is gluon (JavaFX)

I've never heard of that framework. I've only worked with Flutter, React Native and Ionic. And I would probably prefer Flutter. Because that would also allow us to easly create native apps for desktop as well. 

> PWAs aren't support by some major browsers/OSes. That doesn't mean we can't do it as well though. With a native app we can gradually add things like local storage easily and in a way that the browser won't randomly delete it.

Which browsers/OSes dont support PWA's? But you are right there will be way more control over data handling in a native app.

The Deployment for natvie iOS apps will be hard, since peergos.org will need to become a apple developer. Pay the subscriptions. And adhere to all their policies if anyone should be able to use the native app on iOS.

**Comment by ianopolous** [comment]
Awesome! Can you try building it for iOS (instructions are in the readme)?

Gluon also gives us native desktop apps. It relies on graalVM for native compilation. 

Apple is the main holdout for PWA support. They are clearly worried that it gives people a way around their app store control. https://caniuse.com/web-app-manifest

**Comment by jonaswre** [comment]
`mvn gluonfx:run` works so I guess MacOSX Build works.

`mvn -Pios gluonfx:build gluonfx:package gluonfx:install gluonfx:nativerun` throws the following

Im using a m1 Mac, Java 17 and Graalvm 22.2

```
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< org.peergos:client >-------------------------
[INFO] Building Peergos 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- gluonfx-maven-plugin:1.0.15:build (default-cli) @ client ---
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< org.peergos:client >-------------------------
[INFO] Building Peergos 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> gluonfx-maven-plugin:1.0.15:compile (default-cli) > process-classes @ client >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ client ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ client ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< gluonfx-maven-plugin:1.0.15:compile (default-cli) < process-classes @ client <<<
[INFO] 
[INFO] 
[INFO] --- gluonfx-maven-plugin:1.0.15:compile (default-cli) @ client ---
Sep 29, 2022 10:16:04 AM com.gluonhq.substrate.util.Logger logInfo
INFO: Substrate is tested with the Gluon's GraalVM build which you can find at https://github.com/gluonhq/graal/releases.
While you can still use other GraalVM builds, there is no guarantee that these will work properly with Substrate
[Thu Sep 29 10:16:04 CEST 2022][INFO] ==================== COMPILE TASK ====================
             _______  ___      __   __  _______  __    _
            |       ||   |    |  | |  ||       ||  |  | |
            |    ___||   |    |  | |  ||   _   ||   |_| |
            |   | __ |   |    |  |_|  ||  | |  ||       |
            |   ||  ||   |___ |       ||  |_|  ||  _    |
            |   |_| ||       ||       ||       || | |   |
            |_______||_______||_______||_______||_|  |__|

    Access to the latest docs, tips and tricks and more info on
    how to get support? Register your usage of Gluon Substrate now at

    https://gluonhq.com/activate



[Thu Sep 29 10:16:04 CEST 2022][INFO] We will now compile your code for arm64-apple-ios. This may take some time.
[Thu Sep 29 10:16:04 CEST 2022][INFO] Downloading Java Static Libs...

Download progress: 0,01 / 2,41M
Download progress: 0,24 / 2,41M
Download progress: 0,48 / 2,41M
Download progress: 0,73 / 2,41M
Download progress: 0,97 / 2,41M
Download progress: 1,21 / 2,41M
Download progress: 1,45 / 2,41M
Download progress: 1,69 / 2,41M
Download progress: 1,93 / 2,41M
Download progress: 2,17 / 2,41M
Download progress: 2,41 / 2,41M
[Thu Sep 29 10:16:06 CEST 2022][INFO] Java static libs downloaded successfully
[Thu Sep 29 10:16:06 CEST 2022][INFO] Downloading JavaFX static libs...

Download progress: 0,01 / 26,68M
Download progress: 2,67 / 26,68M
Download progress: 5,34 / 26,68M
Download progress: 8,01 / 26,68M
Download progress: 10,68 / 26,68M
Download progress: 13,34 / 26,68M
Download progress: 16,02 / 26,68M
Download progress: 18,68 / 26,68M
Download progress: 21,35 / 26,68M
Download progress: 24,02 / 26,68M
Download progress: 26,68 / 26,68M
[Thu Sep 29 10:16:18 CEST 2022][INFO] JavaFX static libs downloaded successfully
[Thu Sep 29 10:16:25 CEST 2022][INFO] [SUB] Warning: Ignoring server-mode native-image argument --no-server.
[Thu Sep 29 10:16:26 CEST 2022][INFO] [SUB] ========================================================================================================================
[Thu Sep 29 10:16:26 CEST 2022][INFO] [SUB] GraalVM Native Image: Generating 'org.peergos.sample.main' (shared library)...
[Thu Sep 29 10:16:26 CEST 2022][INFO] [SUB] ========================================================================================================================
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] [1/7] Initializing...                                                                                    (0,0s @ 0,17GB)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] Error: Missing CAP cache value for: NativeCodeInfo:AArch64LibCHelperDirectives:StructInfo:CPUFeatures:StructFieldInfo:fDMB_ATOMICS
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Missing CAP cache value for: NativeCodeInfo:AArch64LibCHelperDirectives:StructInfo:CPUFeatures:StructFieldInfo:fDMB_ATOMICS
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:72)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:66)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.query.QueryResultParser.visitStructInfo(QueryResultParser.java:135)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.info.StructInfo.accept(StructInfo.java:62)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:64)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.info.InfoTreeVisitor.visitNativeCodeInfo(InfoTreeVisitor.java:72)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.query.QueryResultParser.parse(QueryResultParser.java:79)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessorCache.get(CAnnotationProcessorCache.java:166)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:94)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:554)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1617)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1073)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:896)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] ------------------------------------------------------------------------------------------------------------------------
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB]                          0,2s (9,0% of total time) in 8 GCs | Peak RSS: 0,61GB | CPU load: 3,28
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] ========================================================================================================================
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] Failed generating 'org.peergos.sample.main' after 1,8s.
[Thu Sep 29 10:16:27 CEST 2022][INFO] [SUB] Error: Image build request failed with exit status 1
[Thu Sep 29 10:16:27 CEST 2022][SEVERE] Process compile failed with result: 1
Check the log files under /Users/jonaswre/Projects/private/mobile/target/gluonfx/arm64-ios/gvm/log
And please check https://docs.gluonhq.com/ for more information.
[Thu Sep 29 10:16:27 CEST 2022][INFO] Logging process [compile] to file: /Users/jonaswre/Projects/private/mobile/target/gluonfx/log/process-compile-1664439387335.log
[Thu Sep 29 10:16:27 CEST 2022][SEVERE] Compiling failed.
Check the log files under /Users/jonaswre/Projects/private/mobile/target/gluonfx/arm64-ios/gvm/log
And please check https://docs.gluonhq.com/ for more information.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.503 s
[INFO] Finished at: 2022-09-29T10:16:27+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.15:compile (default-cli) on project client: Compiling failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Skipping Peergos
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.356 s
[INFO] Finished at: 2022-09-29T10:16:27+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.15:build (default-cli) on project client: Error, gluonfx:build failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by ianopolous** [comment]
I think you need the gluon version of graalvm from here: https://github.com/gluonhq/graal/releases/tag/gluon-22.1.0.1-Final

**Comment by jonaswre** [comment]
```
[Thu Sep 29 12:03:41 CEST 2022][FINE] Start process compile-additional-sources...
[Thu Sep 29 12:03:41 CEST 2022][FINE] [SUB] AppDelegate.m:30:10: fatal error: 'jni.h' file not found
[Thu Sep 29 12:03:41 CEST 2022][FINE] [SUB] #include "jni.h"
[Thu Sep 29 12:03:41 CEST 2022][FINE] [SUB]          ^~~~~~~
[Thu Sep 29 12:03:41 CEST 2022][FINE] [SUB] 1 error generated.
[Thu Sep 29 12:03:41 CEST 2022][FINE] [SUB] JvmFuncsFallbacks.c:4:10: fatal error: 'jni.h' file not found
[Thu Sep 29 12:03:41 CEST 2022][FINE] [SUB] #include <jni.h>
[Thu Sep 29 12:03:41 CEST 2022][FINE] [SUB]          ^~~~~~~
[Thu Sep 29 12:03:41 CEST 2022][FINE] [SUB] 1 error generated.
[Thu Sep 29 12:03:41 CEST 2022][FINE] Result for compile-additional-sources: 1
```

This is now what I get. I've now set GRAALVM_HOME to https://github.com/gluonhq/graal/releases/tag/gluon-22.1.0.1-Final

It seems like jni is missing but there is a jni_md in the java/darwin folder... I'm not to familiar with the graalvm...

**Comment by ianopolous** [comment]
Have you done the two brew installs here: https://docs.gluonhq.com/#platforms_ios

**Comment by jonaswre** [comment]
Yes...

**Comment by ianopolous** [comment]
They command they list for setting graal path is
> export GRAALVM_HOME=/path/to/graalvm-svm-java17-darwin-m1-gluon-22.1.0.1-Final/Contents/Home

do you have the Contents/Home on the end?

**Comment by ianopolous** [comment]
Did you get the java17 or 11 version of graalvm? I'd go with 17.

**Comment by jonaswre** [comment]
I've java 17. Do i need openjdk?

**Comment by ianopolous** [comment]
I'm just referring to the graalvm version (that link has both 11 and 17 versions of graal)

**Comment by jonaswre** [comment]
`graalvm-svm-java17-darwin-m1-gluon-22.1.0.1-Final.tar.gz`this is the file I used

**Comment by ianopolous** [comment]
Ok that's good. And you have the path suffix /Contents/Home ?

**Comment by jonaswre** [comment]
```
Process
=======
compile-additional-sources

Command Line
============
clang -c -DSUBSTRATE -xobjective-c -arch arm64 -mios-version-min=11.0 -I./gluon/Contents/Home/include -I./gluon/Contents/Home/include/darwin -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk -DGVM_17 -I/Users/jonaswre/Projects/private/mobile/target/gluonfx/arm64-ios/gvm/Peergos dummy.c AppDelegate.m JvmFuncsFallbacks.c

Output
======
AppDelegate.m:30:10: fatal error: 'jni.h' file not found
#include "jni.h"
         ^~~~~~~
1 error generated.
JvmFuncsFallbacks.c:4:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^~~~~~~
1 error generated.


Result
======
result: 1
```

Thats the log file.

And this is what I execute 

```
cd <repo>
export GRAALVM_HOME=./gluon/Contents/Home && mvn -Pios gluonfx:build gluonfx:package gluonfx:install gluonfx:nativerun
```

**Comment by ianopolous** [comment]
It seems like jni.h is at gluon/Contents/Home/includes/
Maybe it doesn't like the relative path? Could you try an absolute path?

**Comment by ianopolous** [comment]
I've just noticed another doc suggesting also setting:
> export JAVA_HOME=$GRAALVM_HOME

**Comment by ianopolous** [comment]
It should generate a bunch of icons for iOS in target/gluonfx/arm64-ios/gensrc/ios/ would you be able to zip that up and send it to me so I can commit it to override them (they'll be the G logo for Gluon)?

**Comment by jonaswre** [comment]
This is the whole assets folder.

[assets.zip](https://github.com/Peergos/Peergos/files/9676845/assets.zip)

**Comment by ianopolous** [comment]
Ok I've commited some icons for iOS in what I think is the right place. Is it easy for you to check if they are included?

**Comment by jonaswre** [comment]
I can confirm, it now launches correctly on iOS and the icons are shown correctly.

**Comment by ianopolous** [comment]
Fantastic! Thank you. In another branch I've got it running a localhost server (which still just proxies to peergos.net) and connecting to it, but I haven't figured out how to get the web assets to be picked up yet.

**Comment by jonaswre** [comment]
If the web assets are present in the app you should be able to just serve them in the webserver. That's at least how I would do it flutter.

**Comment by ianopolous** [comment]
Does it work correctly on iOS? Specifically upload, download, apps like the text editor, and playing a movie?

**Comment by jonaswre** [comment]
Haven't tested that. I just checked that it launches. I will test these functions later.
I'm only using iOS for development purposes. I'm daily driving Android.

**Comment by jonaswre** [comment]
Okay I've now tested it.

- Upload works from gallery but directly from camera crashes the app.
- Download of small files. Toasts opens and finshies but no file is downloaded.
- Download of large file. App crashes. (Need to sign In again) 
- Playing large files. Same as when downloading
- Playing small files works.

**Comment by ianopolous** [comment]
It seems like we have lots of problems to fix on iOS. I suspect these apply to the website as well if opened in a normal browser?

**Comment by jonaswre** [comment]
That's what I thought as well. I will give it a try and give you feedback. But I'm away over the weekend so don't expect feedback before Tuesday

**Comment by ianopolous** [comment]
Good to know. Thank you. So it's Safari on iOS (or any browser as they all must use the same engine I believe).

**Comment by jonaswre** [comment]
I'll check chrome and safari on iOS to see if you are correct.

**Comment by ianopolous** [comment]
Peergos is now a full PWA will 100% offline login and viewing of recent files, including built-in apps and custom 3rd-party apps. 

We will try again for a full node mobile app when we have a Java implementation of ipfs-nucleus.
